### ISSUE TITLE
KeyError in config due to breaking change in opentelemetry

### ISSUE THREAD

**Issue by ghost** [hashicorp/nomad-open-telemetry-getting-started#2]
The config files in this example error out with key errors due to a breaking change in https://github.com/open-telemetry/opentelemetry-collector/pull/4063. As of now the insecure key needs to be nested under tls
ie
```
exporters:
  otlp:
    endpoint: "{{ with service "otlp.otel-demo-collector" }}{{ with index . 0 }}{{ .Address }}:{{ .Port }}{{ end }}{{ end }}"
    insecure: true
```
should be
```
exporters:
  otlp:
    endpoint: "{{ with service "otlp.otel-demo-collector" }}{{ with index . 0 }}{{ .Address }}:{{ .Port }}{{ end }}{{ end }}"
    tls:
      insecure: true
```
